#cloud-config

ntp:
  enabled: true
timezone: UTC
fqdn: ritsuko.shibumi.dev
ssh_pwauth: false
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHlRfwIYqaqWfh5ObpCV5pA+n+KolK64LZ5VyIi5ZjwtEswkDI6KcGDTGcWYY+/XJ42kj7SbYHSCm4t/HAXHgmKDuQPzq72nVY7G1DjYrArGig9ni0/XCJY64s5oBgW8wVPTnbf/wYo+gHqsXO7ZaJKknW7jybmIiMC9hx+BkGugyT2WdVnI/8fXiR7VBArSfPIT/ieuWi+GR/7nIz6X09d77pY+tZzeOfbm2obU3EsIh8KJzoZeeopqOFnxooTGtk3ifL8Sv154KDzPwRnaGKdwd36aljQharAUkRQS3bVZiRx1Jw19+1XT0a8/D70ilAKMX6ilUa+LO9jObd49pUSitVGN6gHV5LBybbXjdaLe62dN9gRttJ24KjoJer1o2PMRxNxjwGgksPXhcyfBgbxmNOnsGYZ90PFdp3CH3eh9V8wmwj/ATPnX0s7pAVIpJt6lvdMfoZoezWhk/N0e0GpLWc7hmhxmEP0GYp5+oLL4n5wGr39uOsjPeqpx5c+QJPgIk0cJpKW8gVOw5T8e72v6r44APy9+XLTx2rAwfKeTBwyQo/yiGRo+gEdrPROOl9bei+eGFApJLtHPGqMP5PzMpY1A67z3D4tZ8zPoIqDoos5O6k04aXkbHjNCOkbwY29PfqZzqZmEo+FGDAhqwzpfc/7e7vDJTLWusIxxaaOQ== chris@motoko"
write_files:
  - content: |
      {
              experimental_http3
      }

      www.nullday.de {
              redir * https://{http.request.host.labels.1}.{http.request.host.labels.0}{path}
      }

      nullday.de {
              redir * https://shibumi.dev{path}
      }

      kurisu.shibumi.dev {
              file_server
              root * /srv/www/{host}/public/
              header {
                      Strict-Transport-Security "max-age=31536000; includeSubDomains; preload; always"
                      Public-Key-Pins "pin-sha256=\"sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=\"; pin-sha256=\"YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg=\"; pin-sha256=\"C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=\"; includeSubdomains; max-age=2629746;"
                      X-Frame-Options "SAMEORIGIN"
                      X-Content-Type-Options "nosniff"
                      X-XSS-Protection "1; mode=block"
                      Content-Security-Policy "default-src 'none'; base-uri 'self'; form-action 'none'; img-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; worker-src 'self'; object-src 'self'; media-src 'self'; frame-ancestors 'none'; manifest-src 'self'; connect-src 'self'"
                      Referrer-Policy "strict-origin"
                      Feature-Policy "geolocation 'none';midi 'none'; sync-xhr 'none';microphone 'none';camera 'none';magnetometer 'none';gyroscope 'none';speaker 'none';fullscreen 'self';payment 'none';"
                      Expect-CT "max-age=604800"
              }
              header /.well-known/openpgpkey/* {
                      Content-Type application/octet-stream
                      Access-Control-Allow-Origin *
              }
              @pdf {
                      path *.pdf
              }
              header @pdf {
                      Content-Security-Policy "default-src 'none'; base-uri 'self'; form-action 'none'; img-src 'self'; script-src 'self'; style-src 'unsafe-inline'; font-src 'self'; worker-src 'self'; object-src 'unsafe-inline'; media-src 'self'; frame-ancestors 'none'; manifest-src 'self'; connect-src 'self'"
              }
              encode {
                      zstd
                      gzip
              }
      }
    path: /root/Caddyfile
    mode: "0655"
runcmd:
  - "dnf install dnf-automatic -y"
  - "systemctl enable dnf-automatic.timer --now"
  - "mkdir -p /srv/www/kurisu.shibumi.dev/public"
  - "dnf install caddy -y"
  - "mv /root/Caddyfile /etc/caddy/Caddyfile"
  - "systemctl enable caddy --now"